CREATE DATABASE IF NOT EXISTS diario;
USE diario;
CREATE TABLE IF NOT EXISTS receita (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(150) NOT NULL UNIQUE,
	descricao VARCHAR(255) NOT NULL,
	image_url VARCHAR(160) NOT NULL
);
CREATE TABLE IF NOT EXISTS ingrediente (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS receita_ingrediente (
	receita_id INT NOT NULL,
	ingrediente_id INT NOT NULL,
	FOREIGN KEY (receita_id) REFERENCES receita (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (ingrediente_id) REFERENCES ingrediente (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY (receita_id, ingrediente_id)
);
CREATE TABLE IF NOT EXISTS despensa (
	id INT PRIMARY KEY AUTO_INCREMENT,
	ingrediente_id INT NOT NULL UNIQUE,
	quantidade FLOAT NOT NULL,
	FOREIGN KEY (ingrediente_id) REFERENCES ingrediente (id)
);
